stages:
  - build
  - test
  - deploy

job 0:
  stage: .pre
  script: echo "make something useful before build stage"
  

job 1:
  stage: build
  script: echo "make build dependencies"

job 2:
  stage: build
  script: echo "make build artifacts"



