image: java:8-jdk
stages:
 - const
 - build
 - test
 - deploy

const:
 stage: const
 script:
    - uname
 tags:
    - grad
build:
  stage: build
  script:
    - mvn install
  tags:
    - grad

test:
  stage: test
  script:
    - mvn test
  tags:
    - grad
    
deploy:
    stage: deploy
    script:
      - git remote add heroku https://git.heroku.com/asdc-group12-test.git || true
      - git push -fq heroku HEAD:master
    only:
      - development
    tags:
    - grad