image: java:8-jdk
stages:
 - build
 - test
 - deploy

before_script:
    - wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    - tar -xvf apache-maven-3.6.3-bin.tar.gz
    - M2_HOME='./apache-maven-3.6.3'
    - PATH="$M2_HOME/bin:$PATH"
    - export PATH
    - touch cred
    - echo "rashmika.ibrahimpatnam@dal.ca" > cred
    - echo "$HEROKU_API" > cred
    - cat cred | heroku login
    
build:
  stage: build
  script:
    - mvn install
  tags:
    - grad

test:
  stage: test
  script:
    - mvn test
  tags:
    - grad
    
deploy:
    stage: deploy
    script:
      - git remote add heroku https://git.heroku.com/asdc-group12-test.git || true
      - git push heroku development:master
    only:
      - development
    tags:
    - grad