image: java:8-jdk
stages:
 - build
 - test
 - deploy

before_script:
    - wget https://mirrors.estointernet.in/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
    - tar -xvf apache-maven-3.6.3-bin.tar.gz
    - M2_HOME='./apache-maven-3.6.3'
    - PATH="$M2_HOME/bin:$PATH"
    - export PATH
    
build:
  stage: build
  script:
    - mvn install
  tags:
    - ugrad

test:
  stage: test
  script:
    - mvn test
  tags:
    - ugrad
    
deploy:
    stage: deploy
    script:
      - git remote add heroku https://heroku:$HEROKU_API@git.heroku.com/asdc-group12-test.git || true
      - git push -fq heroku HEAD:master
    only:
      - development
    tags:
    - ugrad